import Foundation

// MARK: - Localized lookup
//
// Every user-visible string in the app comes from `Localizable.xcstrings`,
// which is generated by `Localization/tools/gen_ios.py` from the shared
// inventory and the 19 locale packs. Keys are the inventory's keys.
//
// The catalog is reached through `NSLocalizedString` rather than
// `String(localized:)` because several lookups are assembled at run time
// (the unit-variant suffix, the tone suffix), and because plural containers
// have to be resolved by `String(format:locale:arguments:)` — the call that
// expands a `.stringsdict` plural variable. Passing an explicit locale is
// what makes both the plural rule and the decimal separator follow the user's
// language rather than the C locale.

enum L {
    /// A string with no arguments.
    static func s(_ key: String) -> String {
        NSLocalizedString(key, comment: "")
    }

    /// A format string with positional arguments.
    ///
    /// Extra arguments are harmless: several rows bake the unit noun into the
    /// sentence instead of taking it as a token, and the caller still passes
    /// it so one call site can serve every language.
    static func f(_ key: String, _ args: CVarArg...) -> String {
        format(key, args)
    }

    static func format(_ key: String, _ args: [CVarArg]) -> String {
        let format = NSLocalizedString(key, comment: "")
        // With nothing to substitute there is nothing to format, and running an
        // argumentless row through `String(format:)` would only give a stray
        // `%` a chance to misbehave. The generator leaves such rows unescaped.
        guard !args.isEmpty else { return format }
        return String(format: format, locale: Locale.current, arguments: args)
    }

    // MARK: Unit-variant rows
    //
    // Gendered articles and numerals (de, fr, es, it, pl), classifiers (zh, th,
    // vi) and Korean particle alternation all break slot-for-slot substitution
    // of the unit noun. Those rows ship as a complete phrase per unit variant
    // under `<key>__<variant>`; the generator writes all six variants in every
    // language, so this lookup can never miss.

    static func unitKey(_ base: String) -> String {
        base + "__" + UnitsConfig.current.variant.rawValue
    }

    /// A whole-phrase unit row. Pass the same arguments the generic row takes;
    /// languages that supply the phrase whole simply ignore them.
    static func unit(_ base: String, _ args: CVarArg...) -> String {
        format(unitKey(base), args)
    }

    // MARK: Casing
    //
    // Turkish has a dotted and a dotless i. A default `uppercased()` turns
    // *İstatistik* into the misspelled *ISTATISTIK*, so uppercase captions go
    // through the user's own locale — and explicitly through `tr` when that is
    // the language, since `Locale.current` may carry a different region.

    static func upper(_ value: String) -> String {
        let code = Locale.current.language.languageCode?.identifier ?? "en"
        if code == "tr" || code == "az" {
            return value.uppercased(with: Locale(identifier: "tr"))
        }
        return value.uppercased(with: Locale.current)
    }

    /// Uppercase a caption straight from the catalog.
    static func upperKey(_ key: String) -> String {
        upper(s(key))
    }
}

// MARK: - Tone variants
//
// Three tones share one set of rows; the suffix picks the surface. The
// branching already existed in the views — this only moves the strings into
// the catalog.

extension Tone {
    /// `_numbers` when the ledger tone is active, `_neutral` otherwise.
    /// Push reuses the neutral surfaces, exactly as it did before.
    var keySuffix: String {
        self == .numbers ? "_numbers" : "_neutral"
    }
}

// MARK: - Calendar
//
// Week start comes from the platform, never from the language: es-419 is split
// internally (AR/CL Monday, MX/CO/PE Sunday), so only `Calendar.current` can
// answer it. Headers are two characters because single letters collide in
// German (Mo/Mi, Di/Do) and Thai Thursday (พฤ) cannot shorten at all.

enum CalendarL10n {
    static var calendar: Calendar { Calendar.current }

    /// 1 = Sunday … 7 = Saturday, as `Calendar` reports it.
    static var firstWeekday: Int { calendar.firstWeekday }

    /// Weekday headers in display order, starting at the locale's first day.
    static var weekdayHeaders: [String] {
        let symbols = calendar.shortWeekdaySymbols
        guard symbols.count == 7 else { return symbols }
        let start = max(0, min(6, firstWeekday - 1))
        return (0 ..< 7).map { twoCharacters(symbols[(start + $0) % 7]) }
    }

    /// Leading day-of-week offset for a month whose first day falls on
    /// `weekday` (1 = Sunday), respecting the locale's first day of the week.
    static func leadingBlanks(firstDayWeekday weekday: Int) -> Int {
        ((weekday - firstWeekday) + 7) % 7
    }

    private static let trailingMarks = CharacterSet(charactersIn: ". \u{00A0}·。、")

    static func twoCharacters(_ symbol: String) -> String {
        let trimmed = symbol.trimmingCharacters(in: trailingMarks)
        return String(trimmed.prefix(2))
    }
}
